# placeholders for clippy and other tools
# Program IDs may not be correct
[env]
NCN_PROGRAM_ID = "5SiK283D1iFSqHvr8vbNWCBjbjRXeEYS79CLax7nosPf"
RESTAKING_PROGRAM_ID = "RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q"
VAULT_PROGRAM_ID = "Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"
